### ISSUE TITLE
Method override for the designated initializer of the superclass '-init' not found

### ISSUE THREAD

**Issue by lakhman** [ide/WebASDKImageManager#5]
In my swift project, I'm getting the following error

![screen shot 2016-03-17 at 18 31 12](https://cloud.githubusercontent.com/assets/1582690/13856873/3dc71a16-ec6f-11e5-8828-c5ae94aedfd8.png)

> /Users/username/xCode/Project/Pods/WebASDKImageManager/WebASDKImageManager/SDWebASDKImageManager.m:8:17: Method override for the designated initializer of the superclass '-init' not found

It's a warning, but kind of annoying, we simply need to override the init method of NSObject when creating our own convenience init.

e.g: in `/WebASDKImageManager/WebASDKImageManager/SDWebASDKImageManager`

```
- (instancetype)init
{
    return [self init];
}
```

This get's rid of the warning in xcode.

**Comment by lakhman** [comment]
Looks like this fix was already done here:

https://github.com/ide/WebASDKImageManager/commit/e19b408362666a7b7dfadf46165b4ac55d864c0d

Can you update the Pod file so we can use the latest version?

Thanks!

**Comment by lakhman** [comment]
I cleared my cocoa pods cache and tried a reinstall, still didn't work.

Instead im using this for now:

    pod 'WebASDKImageManager', :git => 'https://github.com/ide/WebASDKImageManager.git', :commit => 'e19b408362666a7b7dfadf46165b4ac55d864c0d'

Hopefully you can fix/update this when you get a chance!

Thanks!

**Comment by ide** [comment]
Thanks for the heads up -- 1.1.0 is now on CocoaPods.
